#TODO: Set OMP_NUM_THREADS = 4 via environment variables
language: cpp

notifications:
      email: false

install:
    ./install.sh

compiler:
    - mpicc.mpich2

before_install:
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

#env:
#    - TEST_DIR=utils/test
#    - TEST_DIR=libcommon/unit-test
#    - TEST_DIR=libman/unit-test

#branches:
#    except:
#    - branch-name
