#TODO: Set OMP_NUM_THREADS = 4 via environment variables
language: cpp

# 14.04
sudo: required
dist: trusty

notifications:
      email: false

before_install:
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

install:
    sudo ./install.sh

compiler:
    - mpicc.mpich2

script:
    - make clean; make

    # libcommon unit-tests
    - cd libcommon/unit-test
    - ./test_clusters
    - ./test_thd_safe_bool_vector 2 500
    - cd ../..

    # libman unit-tests
    - cd libman/unit-test
    - ./test_kmeans_task_thread 2
    - ./test_kmeans_thread 2
    - ./test_task_queue 2
    - cd ../..

    # utils
    - cd utils/test
    - ./read_rrow_data 50 5 ../../test-data/matrix_r50_c5_rrw.bin
    - cd ../..

    # Test full
    - cd release-test
    - ./test_auto
    - ./test_man
    - cd ..

branches:
    only:
        dev
#    except:
#    - branch-name
