#TODO: Set OMP_NUM_THREADS = 4 via environment variables
language: cpp

# 14.04
sudo: required
dist: trusty

notifications:
      email: false

before_install:
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

install:
    sudo ./install.sh

compiler:
    - mpicc.mpich2

script:
    - make clean; make
    # Test full
    - cd release-test
    - test_auto
    - test_man
    - cd ..
    # First unit-test
    # libcommon
    #- libcommon/unit-test/test_clusters
    #- libcommon/unit-test/test_thd_safe_bool_vector

    # libman
    #- libman/unit-test/test_kmeans_task_thread
    #- libman/unit-test/test_kmeans_thread
    #- libman/unit-test/test_task_queue

    # utils
    #- utils/test/read_rrow_data 50 5 test-data/matrix_r50_c5_rrw.bin

#env:
#    - TEST_DIR=utils/test
#    - TEST_DIR=libcommon/unit-test
#    - TEST_DIR=libman/unit-test

branches:
    only:
        dev
#    except:
#    - branch-name
